# Generated by Django 3.2.23 on 2023-11-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ingradient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingradient',
            field=models.ManyToManyField(to='core.Ingradient'),
        ),
    ]
